Repository DinoTools/monitoring-check_haproxy, pull requests merged in 2022-09, with the labels that each got.

#8 Allow colon in backend names in overrides
  check_haproxy
Labels: Type: Enhancement

#6 Fix parsing of short command-line arguments
  check_haproxy
Labels: Type: Bug

#7 Fix POD documentation
  check_haproxy
Labels: Status: Feedback Needed, Type: Bug

#12 Add docs and pipeline to build pages
  .github/workflows/docs.yml
  .gitignore
  docs/LICENSE.md
  docs/index.md
  docs/index.md.license
  docs/man/.gitignore
  mkdocs.yml
Labels: Type: Enhancement
